### ISSUE TITLE
Undefined symbols for Architecture

### ISSUE THREAD

**Issue by hebertpalomino** [sputnik-ru/Mapbox-iOS-SDK#1]
Hello,

Having an issue with your library. Here's what I'm getting:

```
ld: warning: directory not found for option '-L/Users/stevepalomino/Documents/Developer/twgeorgiaaquarium/Pods/Mapbox-iOS-SDK/Proj4'
ld: warning: ignoring file /Users/stevepalomino/Documents/Developer/twgeorgiaaquarium/Pods/Mapbox-iOS-SDK@sputnik/Proj4/libProj4.a, missing required architecture x86_64 in file /Users/stevepalomino/Documents/Developer/twgeorgiaaquarium/Pods/Mapbox-iOS-SDK@sputnik/Proj4/libProj4.a (2 slices)
Undefined symbols for architecture x86_64:
  "_pj_free", referenced from:
      -[RMProjection dealloc] in libMapbox-iOS-SDK@sputnik.a(RMProjection.o)
  "_pj_fwd", referenced from:
      -[RMProjection coordinateToProjectedPoint:] in libMapbox-iOS-SDK@sputnik.a(RMProjection.o)
  "_pj_init_plus", referenced from:
      -[RMProjection initWithString:inBounds:] in libMapbox-iOS-SDK@sputnik.a(RMProjection.o)
  "_pj_inv", referenced from:
      -[RMProjection projectedPointToCoordinate:] in libMapbox-iOS-SDK@sputnik.a(RMProjection.o)
ld: symbol(s) not found for architecture x86_64
```

Just wondering if you had any insight into this. Thanks!

**Comment by DZamataev** [comment]
@hebertpalomino Hi! This is a known issue. The thing is that i recompiled Proj4 with bitcode enabled but forgot to include x86_64 architectures. So it cannot be run on a simulator. For now you can run it on device and live with it or take your time to configure messy compilation pipeline, as I once did, and recompile it once again with all the architectures enabled. Then, please, consider pull requesting. Good luck!

**Comment by hebertpalomino** [comment]
Great! Thanks for the quick reply!

**Comment by DZamataev** [comment]
@hebertpalomino You are welcome! So what are you going to do?

**Comment by hebertpalomino** [comment]
probably run on device for now and update to newest mapbox as much as that will suck going through the update probably best for future maintenance.

**Comment by DZamataev** [comment]
@hebertpalomino oh, ok. Mapbox guys won't update their code. They quit maintenance of that version. In fact it only works in my fork. And I also won't work on it any time soon.
